namespace PipelineCore
{
    /// <summary>
    /// Represents a conversational agent that interacts with a conversational model.
    /// </summary>
    public class ConversationalAgent
    {
        private ConversationalModel model;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConversationalAgent"/> class.
        /// </summary>
        /// <param name="model">The conversational model to be used by the agent.</param>
        public ConversationalAgent(ConversationalModel model)
        {
            this.model = model;
        }

        /// <summary>
        /// Creates a response using the provided conversational model.
        /// </summary>
        /// <param name="response">The response message to be used for creating the response.</param>
        /// <returns>The response generated by the conversational model.</returns>
        public Response CreateResponse(ResponseMessage response)
        {
            return model.CreateResponse(response);
        }
    }
}
